# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Product' do
  
pod 'AFNetworking'

pod 'MBProgressHUD'

pod 'SDWebImage'

pod 'IQKeyboardManager'

pod 'MJRefresh'

pod 'MJExtension'

pod 'KLCPopup'

pod 'TZImagePickerController'

pod 'JQFMDB'

pod 'MMPopupView'

pod 'SDAutoLayout'

#---------------------------------------#
#分页
# pod 'WMPageController', '~> 2.2.1'
#抽屉
# pod 'MMDrawerController', '~> 0.6.0'
#折线图饼状图
#pod 'JHChart', '~> 1.1.0'

#搜索页面
# pod 'PYSearch', '~> 0.7.5'

end
