# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Product' do
  
pod 'AFNetworking', '~> 3.1.0'

pod 'MBProgressHUD', '~> 1.0.0'

pod 'SDWebImage','~> 4.0.0'

pod 'IQKeyboardManager','~> 4.0.9'

pod 'MJRefresh','~> 3.1.12'

pod 'YYModel','~> 1.0.4'

pod 'KLCPopup','~> 1.0'

pod 'TZImagePickerController','~> 1.7.9'

pod 'JQFMDB','~> 1.1.4'

pod 'MMPopupView','~> 1.7.2'

pod 'WMPageController','~> 2.2.1'

pod 'pop', '~> 1.0.9'

pod 'ReactiveObjC', '~> 2.1.2'

pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'

#---------------------------------------#

#抽屉
# pod 'MMDrawerController', '~> 0.6.0'
#折线图饼状图
#pod 'JHChart', '~> 1.1.0'

#搜索页面
# pod 'PYSearch', '~> 0.7.5'

end
